services:
  quant_copilot_equity-research-agent:
    build: .
    container_name: quant_copilot_equity-research-agent

    ports:
      - "8000:8000"

    restart: unless-stopped

    environment:
      - PYTHONUNBUFFERED=1